### ISSUE TITLE
Trouble building environment due to 'Unable to locate CUDNN library' error on Mac OS X

### ISSUE THREAD

**Issue by SheddNed** [VIAME/VIAME#106]
Hello,

I am attempted to build the VIAME GUI on my Mac and have been encountering the "Unable to locate CUDNN library" despite having downloaded the correct version of CUDA and cuDNN onto my machine.  I have a working C++ compiler, CMAKE, and git installed.  Any guidance would be greatly appreciated. 

Thank you.

**Comment by mattdawkins** [comment]
Maybe you need to point the CUDNN_LIBRARY cmake variable to wherever you installed CUDNN?

Everything use to work on Mac though I haven't tried it in a while (a year or so) and it dropped out from support, so you may or may not encounter other build errors along the way.

There's also the web GUI if you just want to do annotation.

**Comment by SheddNed** [comment]
Thanks for the quick reply.  I think pivoting away from using Mac makes the most sense.  Both the web GUI and Windows on a different machine are options for me.  

Thanks again.
