### ISSUE TITLE
Should change permissions to 755 to prevent downstream bloat

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME#129]
https://github.com/VIAME/VIAME/blob/af5bffab81c4d1ab616882735c5ec88fe6aca551/cmake/build_server_docker.sh#L120

* This builds as root, so permissions of `/opt/noaa/viame` are whatever they are in this repo.
* Running docker services as root is bad, so I have to chmod in order for my service runner to use any of these files.
* In layered filesystems, chmod causes a full copy, exploding image size.

A `chmod -R 755 /opt/noaa/viame` in these docker scripts would make it so that I didn't have to do this later.

This would save roughly 7GB of space, or reduce my 25GB image to 18GB.

EDIT: I'm checking on whether this is currently necessary, but guaranteeing o+rx I think should be the responsibility of this script.

**Comment by subdavis** [comment]
Yep, this is necessary.  Permissions for /opt/noaa/viame are unusable by uid 1000

Assuming I'm the only user of this thing, I'd really prefer to have you chown  the whole thing to`1000:1000` or something like that. I need to be able to write into these files because I have to pull the models using scripts, and I can't do that as root in a reasonable way.

**Comment by subdavis** [comment]
let's just do chown.

```bash
chown -R 1099:1099 /opt/noaa/viame
```

1099 will be the uid of our worker user.

**Comment by mattdawkins** [comment]
I still want these containers to be robust for non-viame-web users. Though seems like a specialized case for the web server release, will it have adverse effects on the other case?

**Comment by subdavis** [comment]
> will it have adverse effects on the other case?

No.   Other use cases will still tend to use root when running this container.  Root can still do whatever they want, and having a different owner for these files won't matter.  

However, it will give other users the opportunity to run this container properly using a non-root user.

**Comment by mattdawkins** [comment]
It was in the latest build (which succeeded last night)
