### ISSUE TITLE
Support PATH-style search for pipeline includes

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME#131]
It's not always possible to transport a pipe file into `configs/pipelines` so that it can include other pipes.

It would be great to support some kind of `export VIAME_INCLUDE_PATH=/opt/noaa/viame/configs/pipelines` so that VIAME knows to search a comma-separated list of directories to satisfy `include` arguments.

**Comment by linus-sherrill** [comment]
KWIVER supports this with the `SPROKIT_PIPE_INCLUDE_PATH` environment variable. (Maybe it should be called KWIVER_PIPE_INCLUDE_PATH, but that is another issue.) There is also a default search path that is established at build time using the CMAKE variable `SPROKIT_DEFAULT_PIPE_INCLUDE_PATHS`. These default paths are filled in with some defaults, but you can change or add to the them.  Also note that these paths use a semicolon (';') as a separator.

**Comment by subdavis** [comment]
Thanks!
