### ISSUE TITLE
Clarify minimum NVIDIA driver version

### ISSUE THREAD

**Issue by brianhelba** [VIAME/VIAME#141]
The VIAME [base Docker image](https://github.com/VIAME/VIAME/blob/master/docker/viame_gpu_all_models.docker) uses `nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04`. From [NVIDIA's CUDA release notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html) (Table 3), it seems that the minimum NVIDIA driver version for CUDA 10.1 are 418.39 for Linux and 418.96 for Windows.

However, the [VIAME README](https://github.com/VIAME/VIAME/blob/master/README.md) indicates that the minimum NVIDIA driver version is 451.82. Version 451.82 exactly is apparently [a Widows-only data center driver](https://www.nvidia.com/download/driverResults.aspx/162631/en-us), so I will assume that the README is more generally requiring a minimum driver version ~450.

Is the minimum NVIDIA driver version really ~450, or is ~418 acceptable?

**Comment by mattdawkins** [comment]
418 is acceptable short term though I've had people with RTX 3080 cards want CUDA 11 which has a 451 minimum, the announced 451 is so that people aren't surprised when the cuda 10.1 -> 11 transition happens in near future

**Comment by brianhelba** [comment]
@mattdawkins Thanks for the info. If you're happy with the current docs or think this will be resolved in the near future, feel free to close this issue. I just wanted to note an apparent inconsistency.
