### ISSUE TITLE
VIAME Dive not responding while training a model

### ISSUE THREAD

**Issue by alexabngn** [VIAME/VIAME#155]
Hello, 
Trying to figure out what's wrong, the VIAME Dive desktop currently shows a "Not responding" status on the title bar. Currently training a model and the last line on the log is on info registration on the path for kwiver plugins.

Has anyone ever experienced this issue or is there anyway to solve the issue without starting the training all over again?

Thank you for the help.

**Comment by mattdawkins** [comment]
Sorry for the delayed response - my guess is your training run never started in the first place if you never saw any additional output. Are you still having issues on the latest version?

**Comment by mattdawkins** [comment]
Closing the issue for now, but if you still have issues on latest please post an issue on the DIVE issues board: https://github.com/Kitware/dive/issues
