### ISSUE TITLE
DIVE Desktop not working on Windows

### ISSUE THREAD

**Issue by NatashaHynes** [VIAME/VIAME#158]
I was using DIVE desktop on my Mac, but realized that pipelines cannot be run from this desktop annotator on a Mac, so I am trying to switch my project over to my Windows machine. I am able to open the folder with my images in it and the .json file with my previous annotations, but the DIVE app stays forever in the loading phase. I tried also to without adding the .json right away, and still no luck. Any ideas on what the issue could be? It worked perfectly on my Mac.
![Capture](https://user-images.githubusercontent.com/125378972/218770927-aa7d1c78-b069-4776-8b00-62b8fdf16f0b.PNG)

**Comment by mattdawkins** [comment]
Do you still get issues on latest version? Does it happen with all types of imagery or only a certain type for you? There's example imagery in examples/example_imagery - If only a certain type, please upload an example image.

**Comment by mattdawkins** [comment]
Closing the issue for now, but if you still have issues on latest please post an issue on the DIVE issues board: https://github.com/Kitware/dive/issues
