### ISSUE TITLE
use newer Darknet fork

### ISSUE THREAD

**Issue by stephanecharette** [VIAME/VIAME#177]
The old Joseph Redmon Darknet fork was abandoned 6 years ago!

Please use the new supported Darknet:  https://github.com/hank-ai/darknet#table-of-contents

**Comment by mattdawkins** [comment]
We don't use the old darknet fork, we use Alexey's which was developed up until 1 year ago (which is mostly deprecated regardless, just still in the system for 1-2 projects that still use it)

**Comment by stephanecharette** [comment]
The AlexeyAB fork was abandoned in July 2021, 3 years ago.

The new Darknet repo is the Hank.ai fork.
